# 开发环境配置
server:
  # 服务端口
  port: 8093
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  # 这里进行配置文件设置 pom.xml  后面学习配置 配置隔离
  profiles:
    # 这部分进行选择什么配置文件(这里是默认test  本地开发)
    active: prod

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml



